### ISSUE TITLE
GitHub has deprecated using HTTPS auth to push commits

### ISSUE THREAD

**Issue by quackduck** [gleich/new_yearify#1]
This line makes this HTTPS only :(

https://github.com/gleich/new_yearify/blob/main/pkg/update/clone.go#L10

Please consider adding an ssh option!

**Comment by quackduck** [comment]
This would prolly do it, right?

```go
func SSHClone(repo api.Repo) error {
	err := exec.Command("git", "clone", "git@github.com:" + repo.NameWithOwner).Run()
	if err != nil {
		return err
	}
	return nil
}
```
(this is the kind of string we want: `git@github.com:quackduck/tii`)

**Comment by gleich** [comment]
Hey @quackduck! Thanks for reporting on this. Taking a look rn

**Comment by gleich** [comment]
Pushing new release 😎

**Comment by quackduck** [comment]
eyy let's go
